Traceback (most recent call last):
  File "northern_lights.py", line 93, in <module>
    open_browser(hide=True)
  File "northern_lights.py", line 54, in open_browser
    navigate(browser)
  File "northern_lights.py", line 83, in navigate
    send_email(f'Northern Lights Warning!\n\nGradient: {np.min(dy)}')
  File "northern_lights.py", line 39, in send_email
    mail.login(f'{user.FROM_EMAIL}', f'{user.FROM_PASSWORD}')
  File "/usr/lib/python3.8/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/lib/python3.8/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials y196sm410233lfa.0 - gsmtp')
